//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFormularios.ReferenciaWEB {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WEB.com/", ConfigurationName="ReferenciaWEB.ServicioWEB")]
    public interface ServicioWEB {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento name del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://WEB.com/ServicioWEB/helloRequest", ReplyAction="http://WEB.com/ServicioWEB/helloResponse")]
        ProyectoFormularios.ReferenciaWEB.helloResponse hello(ProyectoFormularios.ReferenciaWEB.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WEB.com/ServicioWEB/helloRequest", ReplyAction="http://WEB.com/ServicioWEB/helloResponse")]
        System.Threading.Tasks.Task<ProyectoFormularios.ReferenciaWEB.helloResponse> helloAsync(ProyectoFormularios.ReferenciaWEB.helloRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://WEB.com/ServicioWEB/validacionRequest", ReplyAction="http://WEB.com/ServicioWEB/validacionResponse")]
        ProyectoFormularios.ReferenciaWEB.validacionResponse validacion(ProyectoFormularios.ReferenciaWEB.validacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WEB.com/ServicioWEB/validacionRequest", ReplyAction="http://WEB.com/ServicioWEB/validacionResponse")]
        System.Threading.Tasks.Task<ProyectoFormularios.ReferenciaWEB.validacionResponse> validacionAsync(ProyectoFormularios.ReferenciaWEB.validacionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="hello", Namespace="http://WEB.com/", Order=0)]
        public ProyectoFormularios.ReferenciaWEB.helloRequestBody Body;
        
        public helloRequest() {
        }
        
        public helloRequest(ProyectoFormularios.ReferenciaWEB.helloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public helloRequestBody() {
        }
        
        public helloRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="helloResponse", Namespace="http://WEB.com/", Order=0)]
        public ProyectoFormularios.ReferenciaWEB.helloResponseBody Body;
        
        public helloResponse() {
        }
        
        public helloResponse(ProyectoFormularios.ReferenciaWEB.helloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public helloResponseBody() {
        }
        
        public helloResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validacion", Namespace="http://WEB.com/", Order=0)]
        public ProyectoFormularios.ReferenciaWEB.validacionRequestBody Body;
        
        public validacionRequest() {
        }
        
        public validacionRequest(ProyectoFormularios.ReferenciaWEB.validacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class validacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        public validacionRequestBody() {
        }
        
        public validacionRequestBody(string usuario, string pass) {
            this.usuario = usuario;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validacionResponse", Namespace="http://WEB.com/", Order=0)]
        public ProyectoFormularios.ReferenciaWEB.validacionResponseBody Body;
        
        public validacionResponse() {
        }
        
        public validacionResponse(ProyectoFormularios.ReferenciaWEB.validacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class validacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int @return;
        
        public validacionResponseBody() {
        }
        
        public validacionResponseBody(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioWEBChannel : ProyectoFormularios.ReferenciaWEB.ServicioWEB, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioWEBClient : System.ServiceModel.ClientBase<ProyectoFormularios.ReferenciaWEB.ServicioWEB>, ProyectoFormularios.ReferenciaWEB.ServicioWEB {
        
        public ServicioWEBClient() {
        }
        
        public ServicioWEBClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioWEBClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWEBClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWEBClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoFormularios.ReferenciaWEB.helloResponse ProyectoFormularios.ReferenciaWEB.ServicioWEB.hello(ProyectoFormularios.ReferenciaWEB.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            ProyectoFormularios.ReferenciaWEB.helloRequest inValue = new ProyectoFormularios.ReferenciaWEB.helloRequest();
            inValue.Body = new ProyectoFormularios.ReferenciaWEB.helloRequestBody();
            inValue.Body.name = name;
            ProyectoFormularios.ReferenciaWEB.helloResponse retVal = ((ProyectoFormularios.ReferenciaWEB.ServicioWEB)(this)).hello(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoFormularios.ReferenciaWEB.helloResponse> ProyectoFormularios.ReferenciaWEB.ServicioWEB.helloAsync(ProyectoFormularios.ReferenciaWEB.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoFormularios.ReferenciaWEB.helloResponse> helloAsync(string name) {
            ProyectoFormularios.ReferenciaWEB.helloRequest inValue = new ProyectoFormularios.ReferenciaWEB.helloRequest();
            inValue.Body = new ProyectoFormularios.ReferenciaWEB.helloRequestBody();
            inValue.Body.name = name;
            return ((ProyectoFormularios.ReferenciaWEB.ServicioWEB)(this)).helloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoFormularios.ReferenciaWEB.validacionResponse ProyectoFormularios.ReferenciaWEB.ServicioWEB.validacion(ProyectoFormularios.ReferenciaWEB.validacionRequest request) {
            return base.Channel.validacion(request);
        }
        
        public int validacion(string usuario, string pass) {
            ProyectoFormularios.ReferenciaWEB.validacionRequest inValue = new ProyectoFormularios.ReferenciaWEB.validacionRequest();
            inValue.Body = new ProyectoFormularios.ReferenciaWEB.validacionRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.pass = pass;
            ProyectoFormularios.ReferenciaWEB.validacionResponse retVal = ((ProyectoFormularios.ReferenciaWEB.ServicioWEB)(this)).validacion(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoFormularios.ReferenciaWEB.validacionResponse> ProyectoFormularios.ReferenciaWEB.ServicioWEB.validacionAsync(ProyectoFormularios.ReferenciaWEB.validacionRequest request) {
            return base.Channel.validacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoFormularios.ReferenciaWEB.validacionResponse> validacionAsync(string usuario, string pass) {
            ProyectoFormularios.ReferenciaWEB.validacionRequest inValue = new ProyectoFormularios.ReferenciaWEB.validacionRequest();
            inValue.Body = new ProyectoFormularios.ReferenciaWEB.validacionRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.pass = pass;
            return ((ProyectoFormularios.ReferenciaWEB.ServicioWEB)(this)).validacionAsync(inValue);
        }
    }
}
